##image maken voor de application zelf
services:
  app:
    image: eclipse-temurin:17-jdk-alpine
    restart: always
    build:
      context: .
    ports:
      - 9090:9090
    working_dir: /spring-petclinic
##    volumes:
##      - /tmp

#image maken voor de database zelf (heb de oude databse dingen hier verwijderd, kan gebruiken als het helemaal niet lukt.)
  db:
    image: postgres:15.2
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./src/main/resources/db/postgres/:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_DB: jdbc:postgresql://postgres:5432/petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
